FROM --platform=linux/arm64 alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates curl && \
    apk add --no-cache docker

COPY drone-image-migrate /app/

ENTRYPOINT [ "/app/drone-image-migrate" ]