FROM alpine:latest

ENV GODEBUG netdns=go
# Install Skopeo
RUN apk --no-cache add ca-certificates curl && \
    apk add --no-cache skopeo

ADD release/linux/arm64/drone-migrate /bin/
ENTRYPOINT ["/bin/drone-migrate"]